name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - env:
          SUPER_SECRET: ${{ secrets.ONE }}
        run: |
          echo $(( ${{ secrets.ONE }} + 1 ))
      - run: |
          echo $(( ${{ secrets.TWO }} + 1 ))
